version: "3.8"

services:
  db:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: my-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
